In [13]:
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import cv2

In [14]:
I = Image.open('stereo2012a.jpg');
img = cv2.imread('stereo2012a.jpg')

uv = np.array([(266.59219819251496, 210.692364130062), 
      (343.2142034312044, 198.84360043335744), 
      (274.49137399031804, 262.0370068157818), 
      (350.32346164922717, 249.39832553929693), 
      (282.390549788121, 310.2219791823803), 
      (356.64280228746964, 296.0034627463349)
     ])
XYZ = np.array([(0,21,7),
      (7,21,0),
       (0,14,7),
       (7,14,0),
       (0,7,7),
       (7,7,0)
      ])
print(img.shape)
print(uv.shape)
print(XYZ.shape)

(576, 768, 3)
(6, 2)
(6, 3)


In [20]:
'''
%% TASK 1: CALIBRATE
%
% Function to perform camera calibration
%
% Usage:   calibrate(image, XYZ, uv)
%          return C
%   Where:   image - is the image of the calibration target.
%            XYZ - is a N x 3 array of  XYZ coordinates
%                  of the calibration target points. 
%            uv  - is a N x 2 array of the image coordinates
%                  of the calibration target points.
%            K   - is the 3 x 4 camera calibration matrix.
%  The variable N should be an integer greater than or equal to 6.
%
%  This function plots the uv coordinates onto the image of the calibration
%  target. 
%
%  It also projects the XYZ coordinates back into image coordinates using
%  the calibration matrix and plots these points too as 
%  a visual check on the accuracy of the calibration process.
%
%  Lines from the origin to the vanishing points in the X, Y and Z
%  directions are overlaid on the image. 
%
%  The mean squared error between the positions of the uv coordinates 
%  and the projected XYZ coordinates is also reported.
%
%  The function should also report the error in satisfying the 
%  camera calibration matrix constraints.
% 
% your name, date 
% Jieli Jerry Zheng, 5.17.2021
'''

'\n%% TASK 1: CALIBRATE\n%\n% Function to perform camera calibration\n%\n% Usage:   calibrate(image, XYZ, uv)\n%          return C\n%   Where:   image - is the image of the calibration target.\n%            XYZ - is a N x 3 array of  XYZ coordinates\n%                  of the calibration target points. \n%            uv  - is a N x 2 array of the image coordinates\n%                  of the calibration target points.\n%            K   - is the 3 x 4 camera calibration matrix.\n%  The variable N should be an integer greater than or equal to 6.\n%\n%  This function plots the uv coordinates onto the image of the calibration\n%  target. \n%\n%  It also projects the XYZ coordinates back into image coordinates using\n%  the calibration matrix and plots these points too as \n%  a visual check on the accuracy of the calibration process.\n%\n%  Lines from the origin to the vanishing points in the X, Y and Z\n%  directions are overlaid on the image. \n%\n%  The mean squared error between the pos

In [106]:
#####################################################################
def calibrate(im, XYZ, uv):
    # TBD
    C = np.zeros((4,3))
    n_points = XYZ.shape[0]
    
    # generate scaling factor
    w_0 = 1
    w = np.ones((n_points,w_0))
    
    # transform to homogeneous system
    X = np.hstack([XYZ,w])
    x = np.hstack([uv,w])
    
    # Factorizing unknowns w/ 2 equations
    A = []
    for i in range(n_points):
        zero_vector = np.zeros((4,1))
        fst_row = np.concatenate([zero_vector.T,-w_0*X[i].reshape(1,4),x[i][1]*X[i].reshape(1,4)],axis=1)
        snd_row = np.concatenate([w_0*X[i].reshape(1,4),zero_vector.T,-x[i][0]*X[i].reshape(1,4)],axis=1)
        A.append(fst_row)
        if i != n_points-1:
            A.append(snd_row)
    A = np.array(A)
    A = np.squeeze(A,axis=1)
#     print(A.shape)
    U,SIGMA,VH = np.linalg.svd(A)
    print(U.shape)
    print(SIGMA.shape)
    print(VH.shape)
    p = VH[:,-1]
    print(p)
    print(np.sqrt(sum([item**2 for item in p])))
    P = p.reshape((3,4))
    print(P)
    return C

In [107]:
ans = calibrate(img,XYZ,uv)

(11, 11)
(11,)
(12, 12)
[-5.95227555e-02 -1.51238886e-02  1.88263998e-01  6.00816023e-04
 -1.57948313e-04  2.00946079e-04 -2.45277752e-04  8.22713372e-05
  4.11798485e-04 -6.54676472e-01  7.29231991e-01  2.00931133e-02]
1.0000000000000002
[[-5.95227555e-02 -1.51238886e-02  1.88263998e-01  6.00816023e-04]
 [-1.57948313e-04  2.00946079e-04 -2.45277752e-04  8.22713372e-05]
 [ 4.11798485e-04 -6.54676472e-01  7.29231991e-01  2.00931133e-02]]


In [ ]:
'''
%% TASK 2: 
% Computes the homography H applying the Direct Linear Transformation 
% The transformation is such that 
% p = np.matmul(H, p.T), i.e.,
% (uBase, vBase, 1).T = np.matmul(H, (u2Trans , v2Trans, 1).T)
% Note: we assume (a, b, c) => np.concatenate((a, b, c), axis), be careful when 
% deal the value of axis 
%
% INPUTS: 
% u2Trans, v2Trans - vectors with coordinates u and v of the transformed image point (p') 
% uBase, vBase - vectors with coordinates u and v of the original base image point p  
% 
% OUTPUT 
% H - a 3x3 Homography matrix  
% 
% your name, date 
% Jieli Jerry Zheng, 5.17.2021
'''

In [3]:
############################################################################
def homography(u2Trans, v2Trans, uBase, vBase):
    H = None
    return H 


############################################################################
def rq(A):
    # RQ factorisation

    [q,r] = np.linalg.qr(A.T)   # numpy has QR decomposition, here we can do it 
                                # with Q: orthonormal and R: upper triangle. Apply QR
                                # for the A-transpose, then A = (qr).T = r.T@q.T = RQ
    R = r.T
    Q = q.T
    return R,Q